#!/usr/bin/env bash
# a script that blocks all incoming traffic except ports 22, 443 and 80.

sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
